startDelaySeconds: 0
ssl: false
lowercaseOutputName: false
lowercaseOutputLabelNames: false
rules:
- pattern: "com.mongodb.kafka.connect<type=([^:]+), task=([^:]+)><>([^:]+)"
  name: "mdb_ksoc_mongodb_metrics_$1_$2_$3"
  labels:
    task: "$3"
    type: "$2"